language: objective-c
xcode_project: SwiftyBeaver.xcodeproj
xcode_scheme: SwiftyBeaver (iOS)
osx_image: xcode7.3
xcode_sdk: iphonesimulator9.3
before_install:  # to fix xctool issue since Xcode 7.3
- brew uninstall xctool && brew install --HEAD xctool
